
#trigger:
#  branches:
#    include:
#      - main

parameters:
  - name: runDestroy
    displayName: Run Destroy Stage?
    type: boolean
    default: false

variables:
  tfWorkingDir: 'tfcode'
  azureServiceConnection: 'technicaldevops'

stages:

# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: Deploy Infrastructure
  jobs:
    - job: TerraformDeploy
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            workingDirectory: $(tfWorkingDir)
            inlineScript: |
              terraform init
              terraform validate
              terraform plan -out=tfplan
              terraform apply -auto-approve tfplan

# =========================
# DESTROY STAGE
# =========================
- stage: Destroy
  displayName: Destroy Infrastructure
  dependsOn: Deploy
  condition: and(succeeded(), eq('${{ parameters.runDestroy }}', true))

  jobs:
    - job: TerraformDestroy
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            workingDirectory: $(tfWorkingDir)
            inlineScript: |
              terraform init
              terraform destroy -auto-approve